# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent
LABEL io.k8s.description="A basic Apache HTTP Server child image, uses ONBUILD" \
 io.k8s.display-name="Apache HTTP Server" \
 io.openshift.expose-services="8080:http" \
 io.openshift.tags="apache, httpd"
LABEL io.openshift.expose-services="8080:http"
EXPOSE 8080
RUN chgrp -R 0 /var/log/httpd /var/run/httpd && \
 chmod -R g=u /var/log/httpd /var/run/httpd
USER 1001
